### PR TITLE
feat: add a way for adding custom template data

### PR DESCRIPTION
**Pull request by mapleeit**

### CODE REVIEW

**Comment by piuccio** [comment]
looks good, but can you explain your use case?
Are you sure it cannot be done with custom scripts?
Can you add a test?

**Comment by mapleeit** [comment]
Thanks for your response. Here is my use case: 

My final changelog should like this, and it will use `private repo` variable. I didn't find a way to add it to the template context. For now, I just add it to the `global` context. But it's not graceful I think.

Didn't find the **custom scripts** you mentioned in the readme. How it works, maybe it can solve my problem?

image

**Comment by piuccio** [comment]
Have a look at this https://github.com/ariatemplates/git-release-notes#post-processing

**Comment by mapleeit** [comment]
This should work for me. But it’s a little weird that provides a file path to load when this lib is used as a module. Could option.script support function type?

**Comment by piuccio** [comment]
I see your point when using the lib as a module. No, it doesn't support functions.
If you feel like implementing it, I prefer supporting postprocessing as a function rather than your current PR, because it's more flexible than just proving extra data to the template.

**Comment by mapleeit** [comment]
Approve of what you suggested. I will make a new PR.

**Pull request closed without merging**
