### PR TITLE
Make commit.authorEmail a valid link #15

### PR DESCRIPTION
**Pull request by rs2**

### CODE REVIEW

**Comment by rs2** [comment]
Shall we merge? :smile:

**Comment by rs2** [comment]
@piuccio Are you OK to initiate a new release and push v0.0.3 to npmjs.com?

**Comment by piuccio** [comment]
I'm quite busy at the moment, I'll try this afternoon hopefully.

**Comment by piuccio** [comment]
just released to `0.0.3` thanks for the PR

**Pull request merged**
