### PR TITLE
Update html.ejs

### PR DESCRIPTION
**Pull request by jaygood**

### CODE REVIEW

**Comment by piuccio** [comment]
thanks, I think the footer div is not closed, I don't have time to check now, do you mind having another look?

**Comment by jaygood** [comment]
The footer looks fine here, though... what is it supposed to provide? There's neither content nor styling.

Other than that, the only warnings that I'm getting are for the unclosed pre tag. Is it self closing?

**Comment by piuccio** [comment]
I think the footer is a mistake, and the `pre` tag needs closing.

I've opened #18 to fix those, would you like to test it and see if it solves your problem?

**Comment by jaygood** [comment]
Looks good!

**Comment by piuccio** [comment]
thanks for checking, closing this

**Pull request closed without merging**
