### PR TITLE
Do not generate same release notes if no changes are detected

### PR DESCRIPTION
**Pull request by alexrus**
When generating RN, if there are no changes the same release notes are being generated.
If -n arg is sent the template will show “No Changes”

A new file "commits.json" was added, this will store the last commit for each project that you generate release notes for.
When generating RN, if the latest commit is the same with the one stored in commits.json, the commits var will be set to an empty array and in this case, the template will show "No Changes"

### CODE REVIEW

**Comment by alexrus** [comment]
@piuccio @jakub-g please review

**Comment by benouat** [comment]
Hello @alexrus, I am not totally convinced by your pull request.
First i don't really like the idea of adding a new file to the repo that contains information that you could read from git.

Second, the name of your new cli parameter is confusing to me. `new` does not feel like detecting no changes.

Third, I doubt about the added value of such a feature. This tool should be considered as `a pure function`. If you call it with the same arguments, it will always return the same thing. So I don't get how you could end up in a situation where there is nothing new...

Could you elaborate a concrete use case ?

**Comment by alexrus** [comment]
@benouat I agree with you on point 2 & 3.
For point 2 I can think for a better cli param name
Point 3 sounds good in theory, however it's something that I find useful, if there are no changes since the last RN generation it should say so.

Here is the use-case for me: We are generating builds every day for two platforms (front-end & back-end). 
For us it's a must that both platforms have new builds that day and with same version number. Sometimes one of the platform does not contain any changes, still, the release notes that are generated tell us otherwise.

Initially I wanted to extend this package and use it directly, but I thought that a PR would be better in case you guys think it might be useful.

**Comment by piuccio** [comment]
I agree with @benouat that this module should be as pure a function as possible.

The cli already supports `since..to` syntax, I think it's cleaner if you extend your builds script:

```
git-release-notes `cat last_commit.txt`..HEAD
git rev-parse HEAD > last_commit.txt
```

If anything I'd prefer extending the syntax to support

`git-release-notes <since_date>..<until_date>`

so that you could run

```
git release-notes `date -v -1d -u +%FT%TZ`..HEAD
```

to generate the release note from any commit in the last 24 hours

**Pull request closed without merging**
